title: Asheesh Devblog
email: asheeshjanghu@gmail.com
description: Hi, I'm a backend engineer and this is my personal blog about backend development.
github_username: asheeshjanghu
minimal_mistakes_skin: default
search: true
logo: "/assets/images/star.ico"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: AU

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Asheesh Janghu"
  avatar : "/assets/images/asheeshProfile.jpg"
  bio    : "Backend Engineer"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/rosiejh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rosiejh"
    - label: "Kaggle"
      icon: "fab fa-fw fa-kaggle"
      url: "https://kaggle.com/rosiejh"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/rosiejh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rosiejh"
    - label: "Kaggle"
      icon: "fab fa-fw fa-kaggle"
      url: "https://kaggle.com/rosiejh"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "disqus"
  disqus:
    shortname: "rosiejh"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
